import React, { useState, useRef } from 'react';
import { Play, Plus, RotateCcw, BookOpen, Loader2, Edit2, Check, ChevronDown } from 'lucide-react';
import { Group, Mantra } from '../types';
import { getMantraInsight } from '../services/geminiService';

interface MantraCounterProps {
  activeGroup: Group | null;
  personalMantras: Mantra[];
  onUpdateCount: (increment: number, groupId: string | null, mantraText: string) => void;
  onAddPersonalMantra: (text: string, target: number) => void;
}

const MantraCounter: React.FC<MantraCounterProps> = ({ activeGroup, personalMantras, onUpdateCount, onAddPersonalMantra }) => {
  const [sessionCount, setSessionCount] = useState(0);
  const [insight, setInsight] = useState<string | null>(null);
  const [isLoadingInsight, setIsLoadingInsight] = useState(false);
  const [manualInput, setManualInput] = useState<string>('');
  const [isManualMode, setIsManualMode] = useState(false);
  
  // Personal Mantra Selection State
  const [selectedPersonalMantraId, setSelectedPersonalMantraId] = useState<string>(personalMantras[0]?.id || '');
  const [isCreatingMantra, setIsCreatingMantra] = useState(false);
  const [newMantraText, setNewMantraText] = useState('');

  const activeMantra = activeGroup 
    ? activeGroup.mantra 
    : personalMantras.find(m => m.id === selectedPersonalMantraId) || { text: 'Om Namah Shivaya', targetCount: 108 };

  const buttonRef = useRef<HTMLButtonElement>(null);

  const handleTap = () => {
    setSessionCount(prev => prev + 1);
    onUpdateCount(1, activeGroup?.id || null, activeMantra.text);
    
    if (navigator.vibrate) {
      navigator.vibrate(10);
    }
  };

  const handleManualSubmit = () => {
    const val = parseInt(manualInput, 10);
    if (!isNaN(val) && val > 0) {
      setSessionCount(prev => prev + val);
      onUpdateCount(val, activeGroup?.id || null, activeMantra.text);
      setManualInput('');
      setIsManualMode(false);
    }
  };

  const fetchInsight = async () => {
    setIsLoadingInsight(true);
    const text = await getMantraInsight(activeMantra.text);
    setInsight(text);
    setIsLoadingInsight(false);
  };

  const handleCreateMantra = () => {
    if (newMantraText.trim()) {
      onAddPersonalMantra(newMantraText, 108);
      setNewMantraText('');
      setIsCreatingMantra(false);
      // The parent will likely append it, logic assumes next render updates list. 
      // We can't auto-select immediately without knowing the new ID generated by parent, 
      // but user can select it from dropdown.
    }
  };

  return (
    <div className="flex flex-col items-center justify-center h-full max-w-md mx-auto w-full py-6 animate-in zoom-in-95 duration-300">
      
      {/* Header Info */}
      <div className="text-center mb-8 w-full">
        <span className="px-3 py-1 bg-stone-200 text-stone-600 rounded-full text-xs font-medium uppercase tracking-wider mb-4 inline-block">
          {activeGroup ? activeGroup.name : "Personal Practice"}
        </span>

        {/* Context Switching (Only if not in group) */}
        {!activeGroup && (
           <div className="mb-4 relative inline-block w-full max-w-xs">
              {isCreatingMantra ? (
                <div className="flex gap-2 animate-in fade-in">
                  <input 
                    type="text" 
                    value={newMantraText}
                    onChange={(e) => setNewMantraText(e.target.value)}
                    placeholder="Enter new mantra..."
                    className="w-full px-3 py-2 text-sm border border-stone-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-saffron-400"
                    autoFocus
                  />
                  <button onClick={handleCreateMantra} className="bg-stone-900 text-white px-3 rounded-lg text-xs font-bold">OK</button>
                  <button onClick={() => setIsCreatingMantra(false)} className="bg-stone-200 text-stone-600 px-3 rounded-lg text-xs">X</button>
                </div>
              ) : (
                <div className="flex items-center justify-center gap-2">
                   <select 
                    value={selectedPersonalMantraId}
                    onChange={(e) => {
                      if (e.target.value === 'add_new') {
                        setIsCreatingMantra(true);
                      } else {
                        setSelectedPersonalMantraId(e.target.value);
                        setSessionCount(0); // Reset session when switching mantra
                      }
                    }}
                    className="appearance-none bg-transparent text-2xl md:text-3xl font-serif font-bold text-stone-800 text-center focus:outline-none cursor-pointer hover:text-saffron-600 transition-colors w-full"
                   >
                     {personalMantras.map(m => (
                       <option key={m.id} value={m.id}>{m.text}</option>
                     ))}
                     <option value="add_new" className="text-saffron-600 font-bold">+ Add New Mantra</option>
                   </select>
                   <ChevronDown size={20} className="text-stone-400 absolute right-0 pointer-events-none md:hidden" />
                </div>
              )}
           </div>
        )}

        {activeGroup && (
            <h1 className="text-2xl md:text-3xl font-serif font-bold text-stone-800 mt-2 leading-snug">
              {activeMantra.text}
            </h1>
        )}

        <button 
          onClick={() => insight ? setInsight(null) : fetchInsight()}
          className="mt-2 text-saffron-600 hover:text-saffron-700 text-sm font-medium flex items-center justify-center gap-1 mx-auto transition-colors"
        >
          {isLoadingInsight ? <Loader2 size={14} className="animate-spin"/> : <BookOpen size={14} />}
          {insight ? "Hide Meaning" : "Understand Meaning"}
        </button>
      </div>

      {/* AI Insight Card */}
      {insight && (
        <div className="bg-saffron-50 border border-saffron-100 p-4 rounded-xl mb-6 text-stone-700 text-sm leading-relaxed max-w-sm text-center shadow-sm animate-in fade-in slide-in-from-top-2">
          <p>{insight}</p>
        </div>
      )}

      {/* Main Counter Display */}
      <div className="relative mb-8 group">
        <div className="absolute inset-0 bg-saffron-200 rounded-full blur-3xl opacity-20 group-hover:opacity-30 transition-opacity"></div>
        <div className="relative w-64 h-64 bg-white rounded-full shadow-[0_8px_30px_rgb(0,0,0,0.04)] border-4 border-stone-50 flex flex-col items-center justify-center transition-transform duration-100 active:scale-95">
           <div className="text-6xl font-bold text-stone-800 font-mono tracking-tighter">
             {sessionCount}
           </div>
           <div className="text-stone-400 text-sm mt-2 font-medium">
             / {activeMantra.targetCount}
           </div>
        </div>
      </div>

      {/* Controls */}
      <div className="w-full space-y-4">
        
        {/* Tap Button */}
        <button
          ref={buttonRef}
          onClick={handleTap}
          className="w-full bg-stone-900 hover:bg-stone-800 active:bg-black text-white rounded-2xl py-6 text-xl font-medium shadow-lg shadow-stone-200 transition-all flex items-center justify-center gap-2"
        >
          <Plus size={24} />
          Chant
        </button>

        {/* Manual Input Toggle */}
        <div className="flex gap-2">
           {!isManualMode ? (
             <button 
                onClick={() => setIsManualMode(true)}
                className="flex-1 bg-white border border-stone-200 hover:bg-stone-50 text-stone-600 py-3 rounded-xl font-medium transition-colors flex items-center justify-center gap-2"
             >
               <Edit2 size={16} /> Add Bulk
             </button>
           ) : (
             <div className="flex-1 flex gap-2 animate-in fade-in">
               <input 
                 type="number" 
                 value={manualInput}
                 onChange={(e) => setManualInput(e.target.value)}
                 placeholder="Qty"
                 className="w-full px-4 py-3 rounded-xl border border-stone-300 focus:ring-2 focus:ring-saffron-400 focus:outline-none"
                 autoFocus
               />
               <button 
                 onClick={handleManualSubmit}
                 className="bg-saffron-500 hover:bg-saffron-600 text-white px-4 rounded-xl"
               >
                 <Check size={20} />
               </button>
               <button 
                 onClick={() => setIsManualMode(false)}
                 className="bg-stone-200 text-stone-600 px-4 rounded-xl"
               >
                 X
               </button>
             </div>
           )}

           <button 
              onClick={() => setSessionCount(0)}
              className="w-16 bg-white border border-stone-200 hover:bg-stone-50 text-stone-400 hover:text-red-500 py-3 rounded-xl font-medium transition-colors flex items-center justify-center"
              title="Reset Session"
           >
             <RotateCcw size={18} />
           </button>
        </div>
      </div>
    </div>
  );
};

export default MantraCounter;